"""
Django settings for dj project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from django.contrib.messages import constants as messages
from django_components import ComponentsSettings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)w4lgi#y$y#5ovx$9t9p-=-=_^w1x9&8por)!jr#f^av)t%+**'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
  'events',
  'django.contrib.admin',
  'django.contrib.auth',
  'django.contrib.contenttypes',
  'django.contrib.sessions',
  'django.contrib.messages',
  'django.contrib.staticfiles',
  'django_components',
]

MIDDLEWARE = [
  'django.middleware.security.SecurityMiddleware',
  'django.contrib.sessions.middleware.SessionMiddleware',
  'django.middleware.common.CommonMiddleware',
  'django.middleware.csrf.CsrfViewMiddleware',
  'django.contrib.auth.middleware.AuthenticationMiddleware',
  'django.contrib.messages.middleware.MessageMiddleware',
  'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dj.urls'

TEMPLATES = [
  {
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [],
    # NOTE: 'APP_DIRS' must stay off because we declare 'loaders' explicitly
    # below (Django forbids setting both). The app_directories loader is
    # included in that list, so app templates still resolve as before.
    'OPTIONS': {
      'context_processors': [
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
      ],
      # Make django-components' tags ({% component %}, {% slot %},
      # {% fill %}, {% component_*_dependencies %}, ...) available in every
      # template without a per-file {% load component_tags %}.
      'builtins': [
        'django_components.templatetags.component_tags',
      ],
      'loaders': [(
        'django.template.loaders.cached.Loader',
        [
          'django.template.loaders.filesystem.Loader',
          'django.template.loaders.app_directories.Loader',
          # Lets template_file / {% component %} resolve from component dirs.
          'django_components.template_loader.Loader',
        ],
      )],
    },
  },
]

# django-components
# https://django-components.github.io/django-components/
# Automatically include any app's `components/` directory under BASE_DIR so
# components live in `./src/django/<app>/components` will be discovered.
APP_COMPONENT_DIRS = [
  p / 'components' for p in BASE_DIR.iterdir()
  if p.is_dir() and (p / 'components').exists()
]

COMPONENTS = ComponentsSettings(
  # Where to look for components. Autodiscovery imports every .py file found
  # under these dirs (recursively), registering any @register()-ed component.
  dirs=[*APP_COMPONENT_DIRS],
)

WSGI_APPLICATION = 'dj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
  'default': {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'db.sqlite3',
  }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
  {
    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
  },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Add django-components' finder so JS/CSS colocated with a component (e.g.
# nav_bar.js / nav_bar.css) is discoverable by the staticfiles app.
STATICFILES_FINDERS = [
  'django.contrib.staticfiles.finders.FileSystemFinder',
  'django.contrib.staticfiles.finders.AppDirectoriesFinder',
  'django_components.finders.ComponentsFileSystemFinder',
]

# Media files (user uploads, e.g. event images)
# https://docs.djangoproject.com/en/5.2/topics/files/

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'


# Authentication
# https://docs.djangoproject.com/en/5.2/topics/auth/default/

# Where @login_required sends anonymous users.
LOGIN_URL = 'login'

# Where login / signup redirect on success.
LOGIN_REDIRECT_URL = 'events'

# No LOGOUT_REDIRECT_URL: leaving it unset lets LogoutView render
# registration/logged_out.html instead of redirecting away immediately.


# Messages
# https://docs.djangoproject.com/en/5.2/ref/contrib/messages/

# Map Django's ERROR level to Bootstrap's `alert-danger`.
MESSAGE_TAGS = {
  messages.ERROR: 'danger',
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
